steps:
  ODS_GW_CC_PROD_CC_USERSETTINGS-200018545:
    operation:
      config: {}
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isMultisource: false
      locationID: 20000010
      locationName: ODS
      materializationType: table
      metadata:
        columns:
          - columnReference:
              columnCounter: 2000153674
              stepCounter: "200018545"
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: ROTATETABLES
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"ROTATETABLES\""
          - columnReference:
              columnCounter: 2000153675
              stepCounter: "200018545"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: LOADCOMMANDID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"LOADCOMMANDID\""
          - columnReference:
              columnCounter: 2000153676
              stepCounter: "200018545"
            dataType: VARCHAR(64)
            defaultValue: ""
            description: ""
            name: PUBLICID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"PUBLICID\""
          - columnReference:
              columnCounter: 2000153677
              stepCounter: "200018545"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: CREATEUSERID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"CREATEUSERID\""
          - columnReference:
              columnCounter: 2000153678
              stepCounter: "200018545"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: NUMOPENCLAIMS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"NUMOPENCLAIMS\""
          - columnReference:
              columnCounter: 2000153679
              stepCounter: "200018545"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: BEANVERSION
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"BEANVERSION\""
          - columnReference:
              columnCounter: 2000153680
              stepCounter: "200018545"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: CANCELALERTDISMISS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"CANCELALERTDISMISS\""
          - columnReference:
              columnCounter: 2000153681
              stepCounter: "200018545"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: RETIRED
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"RETIRED\""
          - columnReference:
              columnCounter: 2000153682
              stepCounter: "200018545"
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: PRINTPAGENUMS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"PRINTPAGENUMS\""
          - columnReference:
              columnCounter: 2000153683
              stepCounter: "200018545"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: CREATETIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"CREATETIME\""
          - columnReference:
              columnCounter: 2000153684
              stepCounter: "200018545"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: STARTUPPAGE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"STARTUPPAGE\""
          - columnReference:
              columnCounter: 2000153685
              stepCounter: "200018545"
            dataType: VARCHAR(255)
            defaultValue: ""
            description: ""
            name: LASTNCLAIMS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"LASTNCLAIMS\""
          - columnReference:
              columnCounter: 2000153686
              stepCounter: "200018545"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: MINCLAIMUPDATE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"MINCLAIMUPDATE\""
          - columnReference:
              columnCounter: 2000153687
              stepCounter: "200018545"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: UPDATEUSERID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"UPDATEUSERID\""
          - columnReference:
              columnCounter: 2000153688
              stepCounter: "200018545"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: UPDATETIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"UPDATETIME\""
          - columnReference:
              columnCounter: 2000153689
              stepCounter: "200018545"
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: SHOWPRINTPREVIEW
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"SHOWPRINTPREVIEW\""
          - columnReference:
              columnCounter: 2000153690
              stepCounter: "200018545"
            dataType: NUMBER(2,1)
            defaultValue: ""
            description: ""
            name: PRINTMARGINS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"PRINTMARGINS\""
          - columnReference:
              columnCounter: 2000153691
              stepCounter: "200018545"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: ID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"ID\""
          - columnReference:
              columnCounter: 2000153692
              stepCounter: "200018545"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRCAPLOC
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"HVRCAPLOC\""
          - columnReference:
              columnCounter: 2000153693
              stepCounter: "200018545"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMP
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"HVRCAPTSTAMP\""
          - columnReference:
              columnCounter: 2000153694
              stepCounter: "200018545"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRCAPUSER
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"HVRCAPUSER\""
          - columnReference:
              columnCounter: 2000153695
              stepCounter: "200018545"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRINTEGKEY
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"HVRINTEGKEY\""
          - columnReference:
              columnCounter: 2000153696
              stepCounter: "200018545"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isBusinessKey: "true"
            name: HVRINTEGSEQ
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"HVRINTEGSEQ\""
          - columnReference:
              columnCounter: 2000153697
              stepCounter: "200018545"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRINTEGTSTAMP
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"HVRINTEGTSTAMP\""
          - columnReference:
              columnCounter: 2000153698
              stepCounter: "200018545"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: HVROP
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"HVROP\""
          - columnReference:
              columnCounter: 2000153699
              stepCounter: "200018545"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: HVRTXCOUNTDOWN
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"HVRTXCOUNTDOWN\""
          - columnReference:
              columnCounter: 2000153700
              stepCounter: "200018545"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRTXSEQ
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"HVRTXSEQ\""
          - columnReference:
              columnCounter: 2000153701
              stepCounter: "200018545"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMPUTC
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"HVRCAPTSTAMPUTC\""
          - columnReference:
              columnCounter: 2000153702
              stepCounter: "200018545"
            dataType: VARCHAR(50)
            defaultValue: ""
            description: ""
            name: HVRCAPTUREKEY
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"HVRCAPTUREKEY\""
          - columnReference:
              columnCounter: 2000153703
              stepCounter: "200018545"
            dataType: NUMBER
            defaultValue: ""
            description: Historical Refresh SEQNO for the HVR Table within the specified window
            isBusinessKey: "true"
            name: HVR_REFRESH_SEQNO
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"HVR_REFRESH_SEQNO\""
          - columnReference:
              columnCounter: 2000153704
              stepCounter: "200018545"
            dataType: VARCHAR(15)
            defaultValue: ""
            description: Batch Number for the Process Cycle
            name: BATCH_NUMBER
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"BATCH_NUMBER\""
          - columnReference:
              columnCounter: 2000153705
              stepCounter: "200018545"
            dataType: VARCHAR(256)
            defaultValue: ""
            description: Record source.
            name: DSS_RECORD_SOURCE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"DSS_RECORD_SOURCE\""
          - columnReference:
              columnCounter: 2000153706
              stepCounter: "200018545"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Load date.
            name: DSS_LOAD_DATE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW\".\"DSS_LOAD_DATE\""
          - columnReference:
              columnCounter: 2000153708
              stepCounter: "200018545"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Date and time the row was created in the data warehouse.
            name: DSS_CREATE_TIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - columnReference:
              columnCounter: 2000153707
              stepCounter: "200018545"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Date and time the row was updated in the data warehouse.
            name: DSS_UPDATE_TIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        sourceMapping:
          - aliases: {}
            customSQL:
              customSQL: ""
            dependencies:
              - locationName: STAGE
                nodeName: STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW
            join:
              joinCondition: FROM {{ ref('STAGE','STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW') }} "STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW"
            name: ODS_GW_CC_PROD_CC_USERSETTINGS
            noLinkRefs: []
      name: ODS_GW_CC_PROD_CC_USERSETTINGS
      overrideSQL: false
      sqlType: "10"
      type: sql
    stepCounter: "200018545"
