steps:
  CC_ILCONFIG-18537:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      description: ""
      locationID: ""
      locationName: RAW_GWC_CC_PROD_VF
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 492775
              stepCounter: 18537
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: BEANVERSION
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 492776
              stepCounter: 18537
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: ENABLED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 492777
              stepCounter: 18537
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: GWCBI___SEQVAL
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 492778
              stepCounter: 18537
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 492779
              stepCounter: 18537
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: PUBLICID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 492780
              stepCounter: 18537
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: SINGLETON
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 492781
              stepCounter: 18537
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRCAPLOC
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 492782
              stepCounter: 18537
            config: {}
            dataType: TIMESTAMP_LTZ(9)
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 492783
              stepCounter: 18537
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMPUTC
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 492784
              stepCounter: 18537
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRCAPUSER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 492785
              stepCounter: 18537
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRINTEGKEY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 492786
              stepCounter: 18537
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRINTEGSEQ
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 492787
              stepCounter: 18537
            config: {}
            dataType: TIMESTAMP_LTZ(9)
            defaultValue: ""
            description: ""
            name: HVRINTEGTSTAMP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 492788
              stepCounter: 18537
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: HVROP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 492789
              stepCounter: 18537
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: HVRTXCOUNTDOWN
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 492790
              stepCounter: 18537
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRTXSEQ
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('RAW_GWC_CC_PROD_VF', 'CC_ILCONFIG') }}
      name: CC_ILCONFIG
      schema: ""
      sqlType: Source
      table: CC_ILCONFIG
      type: sourceInput
    stepCounter: "18537"
