steps:
  STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW-200018498:
    operation:
      config:
        insertStrategy: INSERT
        postSQL: ""
        preSQL: ""
        testsEnabled: true
        truncateBefore: true
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isMultisource: false
      locationID: 20000002
      locationName: STAGE
      materializationType: table
      metadata:
        columns:
          - columnReference:
              columnCounter: 2000260034
              stepCounter: "200018498"
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: ROTATETABLES
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"ROTATETABLES\""
          - columnReference:
              columnCounter: 2000260035
              stepCounter: "200018498"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: LOADCOMMANDID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"LOADCOMMANDID\""
          - columnReference:
              columnCounter: 2000260036
              stepCounter: "200018498"
            dataType: VARCHAR(64)
            defaultValue: ""
            description: ""
            name: PUBLICID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"PUBLICID\""
          - columnReference:
              columnCounter: 2000260037
              stepCounter: "200018498"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: CREATEUSERID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"CREATEUSERID\""
          - columnReference:
              columnCounter: 2000260038
              stepCounter: "200018498"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: NUMOPENCLAIMS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"NUMOPENCLAIMS\""
          - columnReference:
              columnCounter: 2000260039
              stepCounter: "200018498"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: BEANVERSION
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"BEANVERSION\""
          - columnReference:
              columnCounter: 2000260040
              stepCounter: "200018498"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: CANCELALERTDISMISS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"CANCELALERTDISMISS\""
          - columnReference:
              columnCounter: 2000260041
              stepCounter: "200018498"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: RETIRED
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"RETIRED\""
          - columnReference:
              columnCounter: 2000260042
              stepCounter: "200018498"
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: PRINTPAGENUMS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"PRINTPAGENUMS\""
          - columnReference:
              columnCounter: 2000260043
              stepCounter: "200018498"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: CREATETIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"CREATETIME\""
          - columnReference:
              columnCounter: 2000260044
              stepCounter: "200018498"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: STARTUPPAGE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"STARTUPPAGE\""
          - columnReference:
              columnCounter: 2000260045
              stepCounter: "200018498"
            dataType: VARCHAR(255)
            defaultValue: ""
            description: ""
            name: LASTNCLAIMS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"LASTNCLAIMS\""
          - columnReference:
              columnCounter: 2000260046
              stepCounter: "200018498"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: MINCLAIMUPDATE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"MINCLAIMUPDATE\""
          - columnReference:
              columnCounter: 2000260047
              stepCounter: "200018498"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: UPDATEUSERID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"UPDATEUSERID\""
          - columnReference:
              columnCounter: 2000260048
              stepCounter: "200018498"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: UPDATETIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"UPDATETIME\""
          - columnReference:
              columnCounter: 2000260049
              stepCounter: "200018498"
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: SHOWPRINTPREVIEW
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"SHOWPRINTPREVIEW\""
          - columnReference:
              columnCounter: 2000260050
              stepCounter: "200018498"
            dataType: NUMBER(2,1)
            defaultValue: ""
            description: ""
            name: PRINTMARGINS
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"PRINTMARGINS\""
          - columnReference:
              columnCounter: 2000260051
              stepCounter: "200018498"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: ID
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"ID\""
          - columnReference:
              columnCounter: 2000260052
              stepCounter: "200018498"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRCAPLOC
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"HVRCAPLOC\""
          - columnReference:
              columnCounter: 2000260053
              stepCounter: "200018498"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMP
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"HVRCAPTSTAMP\""
          - columnReference:
              columnCounter: 2000260054
              stepCounter: "200018498"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRCAPUSER
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"HVRCAPUSER\""
          - columnReference:
              columnCounter: 2000260055
              stepCounter: "200018498"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRINTEGKEY
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"HVRINTEGKEY\""
          - columnReference:
              columnCounter: 2000260056
              stepCounter: "200018498"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            isBusinessKey: "true"
            name: HVRINTEGSEQ
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_05_SEQNO\".\"HVRINTEGSEQ\""
          - columnReference:
              columnCounter: 2000260057
              stepCounter: "200018498"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRINTEGTSTAMP
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"HVRINTEGTSTAMP\""
          - columnReference:
              columnCounter: 2000260058
              stepCounter: "200018498"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: HVROP
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"HVROP\""
          - columnReference:
              columnCounter: 2000260059
              stepCounter: "200018498"
            dataType: NUMBER(38)
            defaultValue: ""
            description: ""
            name: HVRTXCOUNTDOWN
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"HVRTXCOUNTDOWN\""
          - columnReference:
              columnCounter: 2000260060
              stepCounter: "200018498"
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            name: HVRTXSEQ
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"HVRTXSEQ\""
          - columnReference:
              columnCounter: 2000260061
              stepCounter: "200018498"
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMPUTC
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"HVRCAPTSTAMPUTC\""
          - columnReference:
              columnCounter: 2000260066
              stepCounter: "200018498"
            dataType: VARCHAR(50)
            defaultValue: ""
            description: ""
            name: HVRCAPTUREKEY
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_05_SEQNO\".\"HVRCAPTUREKEY\""
          - columnReference:
              columnCounter: 2000260067
              stepCounter: "200018498"
            dataType: NUMBER
            defaultValue: ""
            description: Historical Refresh SEQNO for the HVR Table within the specified window
            isBusinessKey: "true"
            name: HVR_REFRESH_SEQNO
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_05_SEQNO\".\"HVR_REFRESH_SEQNO\""
          - columnReference:
              columnCounter: 2000260068
              stepCounter: "200018498"
            dataType: VARCHAR(15)
            defaultValue: ""
            description: Batch Number for the Process Cycle
            name: BATCH_NUMBER
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"ODS_CTRL_HVRCAPTSTAMP\".\"BATCH_NUMBER\""
          - columnReference:
              columnCounter: 2000260062
              stepCounter: "200018498"
            dataType: VARCHAR(256)
            defaultValue: ""
            description: Record source.
            name: DSS_RECORD_SOURCE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"DSS_RECORD_SOURCE\""
          - columnReference:
              columnCounter: 2000260063
              stepCounter: "200018498"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Load date.
            name: DSS_LOAD_DATE
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: "\"LOAD_GW_CC_PROD_CC_USERSETTINGS\".\"DSS_LOAD_DATE\""
          - columnReference:
              columnCounter: 2000260065
              stepCounter: "200018498"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Date and time the row was created in the data warehouse.
            name: DSS_CREATE_TIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - columnReference:
              columnCounter: 2000260064
              stepCounter: "200018498"
            dataType: TIMESTAMP
            defaultValue: ""
            description: Date and time the row was updated in the data warehouse.
            name: DSS_UPDATE_TIME
            nullable: "true"
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        sourceMapping:
          - aliases: {}
            customSQL:
              customSQL: ""
            dependencies:
              - locationName: LOAD
                nodeName: LOAD_GW_CC_PROD_CC_USERSETTINGS
              - locationName: STAGE
                nodeName: STG_ODS_GW_CC_PROD_CC_USERSETTINGS_05_SEQNO
              - locationName: ODS
                nodeName: ODS_CTRL_HVRCAPTSTAMP
            join:
              joinCondition: "FROM {{ ref('LOAD','LOAD_GW_CC_PROD_CC_USERSETTINGS') }} \"LOAD_GW_CC_PROD_CC_USERSETTINGS\" JOIN {{ ref('STAGE','STG_ODS_GW_CC_PROD_CC_USERSETTINGS_05_SEQNO') }} \"STG_ODS_GW_CC_PROD_CC_USERSETTINGS_05_SEQNO\"    ON LOAD_GW_CC_PROD_CC_USERSETTINGS.HVRINTEGSEQ = STG_ODS_GW_CC_PROD_CC_USERSETTINGS_05_SEQNO.HVRINTEGSEQ  JOIN {{ ref('ODS','ODS_CTRL_HVRCAPTSTAMP') }} \"ODS_CTRL_HVRCAPTSTAMP\"    ON STG_ODS_GW_CC_PROD_CC_USERSETTINGS_05_SEQNO.HVRCAPTUREKEY = ODS_CTRL_HVRCAPTSTAMP.HVRCAPTUREKEY    "
            name: STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW
            noLinkRefs: []
      name: STG_ODS_GW_CC_PROD_CC_USERSETTINGS_10_NEW
      overrideSQL: false
      sqlType: Stage
      type: sql
    stepCounter: "200018498"
